import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
    {
        _id: '0e28f866-f09a-465c-aec5-3b2510d377ad',
        title: "Rasengan Rush",
        anime: "Naruto",
        price: 5000,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Rasengan_Rush_Naruto_Oversized_T-Shirt.jpg",
        rating: 4,
        original_price: 10000,
        discount_percent: 50
    },
    {
        _id: '04a7b087-cdad-4dae-a0f7-c56ea3643876',
        title: "Eyes Naruto",
        anime: "Naruto",
        price: 5500,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Eyes_Naruto_Oversized_T-Shirt.jpg",
        rating: 4,
        original_price: 10000,
        discount_percent: 45
    },
    {
        _id: 'a0bd9302-d9e9-4f12-999e-78985dae23f5',
        title: "Sharingan Eye",
        anime: "Naruto",
        price: 1000,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Sharingan_Eye_Naruto_Sticker.jpg",
        rating: 5,
        original_price: 2222,
        discount_percent: 55
    },
    {
        _id: '9112211d-38eb-4307-984e-5402c4655bed',
        title: "Naruto and Kurama",
        anime: "Naruto",
        price: 1200,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Naruto_and_Kurama_Naruto_Sticker.jpg",
        rating: 5,
        original_price: 2181,
        discount_percent: 45
    },
    {
        _id: '2c874538-bf1f-4f02-92f4-d4fd57c67b66',
        title: "Sasuke Uchiha",
        anime: "Naruto",
        price: 8000,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Sasuke_Uchiha_Naruto_Figurine.jpg",
        rating: 4,
        original_price: 13333,
        discount_percent: 40
    },
    {
        _id: 'dff9a2fa-199f-448b-9eba-a6f80e4fbdb6',
        title: "Itachi vs. Sasuke",
        anime: "Naruto",
        price: 7000,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Itachi_vs._Sasuke_Naruto_Figurine.jpg",
        rating: 3,
        original_price: 14000,
        discount_percent: 50
    },
    {
        _id: '83923ae3-715c-40a8-a09a-c7cd42a588d6',
        title: "Sukuna's Curse",
        anime: "Jujutsu Kaisen",
        price: 4500,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Sukuna's_Curse_Jujutsu_Kaisen_Oversized_T-Shirt.jpg",
        rating: 3,
        original_price: 10000,
        discount_percent: 55
    },
    {
        _id: 'a0ae2e05-ec92-449e-a67d-d14d59d4cbdf',
        title: "Gojo's Infinity",
        anime: "Jujutsu Kaisen",
        price: 4800,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Gojo's_Infinity_Jujutsu_Kaisen_Oversized_T-Shirt.jpg",
        rating: 4,
        original_price: 8727,
        discount_percent: 45
    },
    {
        _id: 'a2259b11-e649-4b3f-9386-a32b38ec9917',
        title: "Kawaii All Characters JJk",
        anime: "Jujutsu Kaisen",
        price: 1500,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Kawaii_All_Characters_Jujutsu_Kaisen_Sticker.jpg",
        rating: 5,
        original_price: 2727,
        discount_percent: 45
    },
    {
        _id: '859c1758-cdcb-4277-bbc0-341b875b80dd',
        title: "Satoru Gojo's Limitless",
        anime: "Jujutsu Kaisen",
        price: 1800,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Satoru_Gojo's_Limitless_Jujutsu_Kaisen_Sticker.jpg",
        rating: 5,
        original_price: 3000,
        discount_percent: 40
    },
    {
        _id: '5e72e161-fd2c-43da-a8ee-461480d8e4a6',
        title: "Yuji Itadori",
        anime: "Jujutsu Kaisen",
        price: 6000,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Yuji_Itadori_Jujutsu_Kaisen_Figurine.jpg",
        rating: 4,
        original_price: 10000,
        discount_percent: 40
    },
    {
        _id: '7d891980-3365-4921-b36c-0149c94db81e',
        title: "Nobara Kugisaki",
        anime: "Jujutsu Kaisen",
        price: 5500,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Nobara_Kugisaki_Jujutsu_Kaisen_Figurine.jpg",
        rating: 3,
        original_price: 10000,
        discount_percent: 45
    },
    {
        _id: 'e65bce8b-4c51-4f49-ab13-f024995507b9',
        title: "Wings of Freedom",
        anime: "Attack on Titan",
        price: 4000,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Wings_of_Freedom_Attack_on_Titan_Oversized_T-Shirt.jpg",
        rating: 5,
        original_price: 8000,
        discount_percent: 50
    },
    {
        _id: '5bebc22f-bcca-427f-9e68-5e83970b7dde',
        title: "Eren's Titan Rampage",
        anime: "Attack on Titan",
        price: 4500,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Eren's_Titan_Rampage_Attack_on_Titan_Oversized_T-Shirt.jpg",
        rating: 4,
        original_price: 7500,
        discount_percent: 40
    },
    {
        _id: '3fb7758d-6152-417f-ae59-72740273362c',
        title: "Survey Corps Insignia",
        anime: "Attack on Titan",
        price: 1200,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Survey_Corps_Insignia_Attack_on_Titan_Sticker.jpg",
        rating: 4,
        original_price: 2666,
        discount_percent: 55
    },
    {
        _id: '2641386d-2114-4aa9-8348-cde266635859',
        title: "Attack Titan Roar",
        anime: "Attack on Titan",
        price: 1000,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Attack_Titan_Roar_Attack_on_Titan_Sticker.jpg",
        rating: 3,
        original_price: 1818,
        discount_percent: 45
    },
    {
        _id: 'a2128ab9-4736-4aa1-8751-19bd4b198ed9',
        title: "Levi Ackerman",
        anime: "Attack on Titan",
        price: 9000,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/levi.jpg",
        rating: 3,
        original_price: 20000,
        discount_percent: 55
    },
    {
        _id: '6af31614-1de1-449c-97e2-2555b1df9bbb',
        title: "Mikasa Ackerman",
        anime: "Attack on Titan",
        price: 6500,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Mikasa_Ackerman_Attack_on_Titan_Figurine.jpg",
        rating: 3,
        original_price: 10833,
        discount_percent: 40
    },
    {
        _id: '654ac63b-0e87-44a8-9aed-8f5b2633d269',
        title: "L's Deductive Mind",
        anime: "Death Note",
        price: 3500,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/L's_Deductive_Mind_Death_Note_Oversized_T-Shirt.jpg",
        rating: 5,
        original_price: 5833,
        discount_percent: 40
    },
    {
        _id: '3da078a0-0dd4-41d9-88f8-e0607edd7bce',
        title: "Kira's Legacy",
        anime: "Death Note",
        price: 4000,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Kira's_Legacy_Death_Note_Oversized_T-Shirt.jpg",
        rating: 4,
        original_price: 7272,
        discount_percent: 45
    },
    {
        _id: '55b332bf-6d21-465d-a68c-0c60cc1a6886',
        title: "Shinigami Realm",
        anime: "Death Note",
        price: 800,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Shinigami_Realm_Death_Note_Sticker.jpg",
        rating: 4,
        original_price: 1600,
        discount_percent: 50
    },
    {
        _id: 'da79a286-eb16-4443-8dde-9e2940c68613',
        title: "Death Note Rules",
        anime: "Death Note",
        price: 900,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Death_Note_Rules_Death_Note_Sticker.jpg",
        rating: 4,
        original_price: 2000,
        discount_percent: 55
    },
    {
        _id: '8ff7434a-2449-4d02-bc8d-0214c12e7e2a',
        title: "Light Yagami",
        anime: "Death Note",
        price: 5500,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Light_Yagami_Death_Note_Figurine.jpg",
        rating: 3,
        original_price: 11000,
        discount_percent: 50
    },
    {
        _id: '53814136-422c-4c0e-817f-46dea234bb54',
        title: "Light and Ryuk",
        anime: "Death Note",
        price: 6000,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Light_and_Ryuk_Death_Note_Figurine.jpg",
        rating: 2,
        original_price: 12000,
        discount_percent: 50
    },
    {
        _id: '3a66b678-a3d4-4403-a86c-410666c3ffde',
        title: "Water Breathing Forms",
        anime: "Demon Slayer",
        price: 4000,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Water_Breathing_Forms_Demon_Slayer_Oversized_T-Shirt.jpg",
        rating: 4,
        original_price: 8888,
        discount_percent: 55
    },
    {
        _id: '8872128e-ffb9-48e2-a3ef-567c4639db00',
        title: "Demon Slaying Corps",
        anime: "Demon Slayer",
        price: 4500,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Demon_Slaying_Corps_Demon_Slayer_Oversized_T-Shirt.jpg",
        rating: 4,
        original_price: 8181,
        discount_percent: 45
    },
    {
        _id: 'a5cbe3bd-7775-460b-8922-8c61e190bb3f',
        title: "Tanjiro's Nichirin Blade",
        anime: "Demon Slayer",
        price: 1000,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Tanjiro's_Nichirin_Blade_Demon_Slayer_Sticker.jpg",
        rating: 4,
        original_price: 1666,
        discount_percent: 40
    },
    {
        _id: '4e8e24e8-f19a-4ef0-977e-4e583704ed60',
        title: "Nezuko Blood Demon Art",
        anime: "Demon Slayer",
        price: 1200,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Nezuko's_Blood_Demon_Art_Demon_Slayer_Sticker.jpg",
        rating: 5,
        original_price: 2181,
        discount_percent: 45
    },
    {
        _id: '544acf3e-95b4-4d9c-9d1d-a5acb40a8d2f',
        title: "Tanjiro Kamado",
        anime: "Demon Slayer",
        price: 6000,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Tanjiro_Kamado_Demon_Slayer_Figurine.jpg",
        rating: 1,
        original_price: 10909,
        discount_percent: 45
    },
    {
        _id: '0cc97bc3-db62-41e5-820c-02f73f0819eb',
        title: "Zenitsu Agatsuma",
        anime: "Demon Slayer",
        price: 5500,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Zenitsu_Agatsuma_Demon_Slayer_Figurine.jpg",
        rating: 2,
        original_price: 12222,
        discount_percent: 55
    },
    {
        _id: 'a713ff33-2f81-4693-83a8-eae265fe0e45',
        title: "Golden Wind Gang",
        anime: "JoJo's Bizarre Adventure",
        price: 4500,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Golden_Wind_Gang_JoJo's_Bizarre_Adventure_Oversized_T-Shirt.jpg",
        rating: 4,
        original_price: 7500,
        discount_percent: 40
    },
    {
        _id: '3611d3ec-d514-424f-a425-aef29750ce7d',
        title: "Star Platinum",
        anime: "JoJo's Bizarre Adventure",
        price: 4000,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Star_Platinum_JoJo's_Bizarre_Adventure_Oversized_T-Shirt.jpg",
        rating: 4,
        original_price: 7272,
        discount_percent: 45
    },
    {
        _id: '2ab4a865-9806-4a65-902a-6fbfd620c782',
        title: "Stand Users",
        anime: "JoJo's Bizarre Adventure",
        price: 1200,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Stand_Users_JoJo's_Bizarre_Adventure_Sticker.jpg",
        rating: 5,
        original_price: 2400,
        discount_percent: 50
    },
    {
        _id: 'c9410a0d-b3fc-4a49-bd50-96bb111a8eec',
        title: "Joestar Family Crest",
        anime: "JoJo's Bizarre Adventure",
        price: 1000,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Joestar_Family_Crest_JoJo's_Bizarre_Adventure_Sticker.jpg",
        rating: 4,
        original_price: 2000,
        discount_percent: 50
    },
    {
        _id: 'a09069ad-bc7d-41ff-9e9e-9ddf0df7eb78',
        title: "Jotaro Kujo",
        anime: "JoJo's Bizarre Adventure",
        price: 6000,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Jotaro_Kujo_JoJo's_Bizarre_Adventure_Figurine.jpg",
        rating: 5,
        original_price: 10909,
        discount_percent: 45
    },
    {
        _id: '07adb6a5-c335-4389-85da-d02e79807358',
        title: "Dio Brando",
        anime: "JoJo's Bizarre Adventure",
        price: 6500,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/dio.jpg",
        rating: 3,
        original_price: 11818,
        discount_percent: 45
    },
    {
        _id: '9dd3e1e9-8463-4e4a-89ac-a0621946e740',
        title: "Victor and Yuri",
        anime: "Yuri on Ice",
        price: 3500,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Victor_and_Yuri_Yuri_on_Ice_Oversized_T-Shirt.jpg",
        rating: 4,
        original_price: 7000,
        discount_percent: 50
    },
    {
        _id: '01c27da0-741b-42cf-b07d-20acecef169d',
        title: "Eros Performance",
        anime: "Yuri on Ice",
        price: 4000,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Eros_Performance_Yuri_on_Ice_Oversized_T-Shirt.jpg",
        rating: 4,
        original_price: 8888,
        discount_percent: 55
    },
    {
        _id: '9269128e-fb12-4928-a5dc-37220b746bdb',
        title: "Skate Together",
        anime: "Yuri on Ice",
        price: 800,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Skate_Together_Yuri_on_Ice_Sticker.jpg",
        rating: 5,
        original_price: 1777,
        discount_percent: 55
    },
    {
        _id: 'baca2d7d-0952-4dc9-a9f8-1fd357c20289',
        title: "All characters yuri on ice",
        anime: "Yuri on Ice",
        price: 900,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/All_characters_Yuri_on_Ice_Sticker.png",
        rating: 5,
        original_price: 1500,
        discount_percent: 40
    },
    {
        _id: '5d150127-f382-49c5-a053-de04465a253b',
        title: "Yuri Katsuki",
        anime: "Yuri on Ice",
        price: 5500,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Yuri_Katsuki_Yuri_on_Ice_Figurine.jpg",
        rating: 3,
        original_price: 11000,
        discount_percent: 50
    },
    {
        _id: '752c3620-0e9e-4510-9b5e-1bbda8f118c7',
        title: "Victor Nikiforov",
        anime: "Yuri on Ice",
        price: 6000,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Victor_Nikiforov_Yuri_on_Ice_Figurine.jpg",
        rating: 3,
        original_price: 13333,
        discount_percent: 55
    },
    {
        _id: 'ffa29e98-fe4e-4d99-891a-2a218eff4658',
        title: "Spy Family Logo",
        anime: "Spy X Family",
        price: 3000,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Spy_Family_Logo_Spy_\u00d7_Family_Oversized_T-Shirt.jpg",
        rating: 4,
        original_price: 5454,
        discount_percent: 45
    },
    {
        _id: '1b72f5b6-1229-4bbe-bf0a-f3ba41cd58df',
        title: "Twilight's Mission",
        anime: "Spy X Family",
        price: 3500,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Twilight's_Mission_Spy_\u00d7_Family_Oversized_T-Shirt.jpg",
        rating: 4,
        original_price: 7777,
        discount_percent: 55
    },
    {
        _id: 'eb418035-1339-4e10-825f-559d1f974d1f',
        title: "Spy Techniques",
        anime: "Spy X Family",
        price: 900,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Spy_Techniques_Spy_\u00d7_Family_Sticker.jpg",
        rating: 4,
        original_price: 1800,
        discount_percent: 50
    },
    {
        _id: '193a47f9-0283-4440-a653-e3174e0a5c40',
        title: "Family Secrets",
        anime: "Spy X Family",
        price: 800,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Family_Secrets_Spy_\u00d7_Family_Sticker.jpg",
        rating: 5,
        original_price: 1454,
        discount_percent: 45
    },
    {
        _id: '1817bcc0-a203-481b-a88d-5cef506b1d75',
        title: "Lloyd Forger",
        anime: "Spy X Family",
        price: 5000,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Lloyd_Forger_Spy_\u00d7_Family_Figurine.jpg",
        rating: 3,
        original_price: 11111,
        discount_percent: 55
    },
    {
        _id: '40f10ff7-aa8a-448f-9564-11aee869581b',
        title: "Yor Forger",
        anime: "Spy X Family",
        price: 4500,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Yor_Forger_Spy_\u00d7_Family_Figurine.jpg",
        rating: 4,
        original_price: 8181,
        discount_percent: 45
    },
    {
        _id: 'f3a8cfb4-eb51-4f94-a132-3733b00e3efe',
        title: "Ai Ohto",
        anime: "Wonder Egg Priority",
        price: 4000,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Ai_Ohto_Wonder_Egg_Priority_Oversized_T-Shirt.jpg",
        rating: 4,
        original_price: 7272,
        discount_percent: 45
    },
    {
        _id: '98b99b4b-eaf2-406a-a083-d8170272e71a',
        title: "Wonder Egg",
        anime: "Wonder Egg Priority",
        price: 4500,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Wonder_Egg_Wonder_Egg_Priority_Oversized_T-Shirt.jpg",
        rating: 4,
        original_price: 8181,
        discount_percent: 45
    },
    {
        _id: 'd26d8b04-35d2-4720-8a75-554d28839aa4',
        title: "Egg of Happiness",
        anime: "Wonder Egg Priority",
        price: 1200,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Egg_of_Happiness_Wonder_Egg_Priority_Sticker.jpg",
        rating: 5,
        original_price: 2666,
        discount_percent: 55
    },
    {
        _id: '99175573-4792-4e54-a964-b4bc9b3afe0f',
        title: "The Silence",
        anime: "Wonder Egg Priority",
        price: 1000,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/The_Silence_Wonder_Egg_Priority_Sticker.jpg",
        rating: 5,
        original_price: 2222,
        discount_percent: 55
    },
    {
        _id: '6a8faa4e-8904-4411-a67a-f68eca890a84',
        title: "Neiru Aonuma",
        anime: "Wonder Egg Priority",
        price: 6000,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Neiru_Aonuma_Wonder_Egg_Priority_Figurine.jpg",
        rating: 3,
        original_price: 10000,
        discount_percent: 40
    },
    {
        _id: 'fc8ee4f4-8691-4465-acce-fdfbf698b26c',
        title: "Rika Kawai",
        anime: "Wonder Egg Priority",
        price: 5500,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Rika_Kawai_Wonder_Egg_Priority_Figurine.jpg",
        rating: 3,
        original_price: 10000,
        discount_percent: 45
    },
    {
        _id: '3dd883e9-fb51-488d-b0d3-99b7c4cd49e2',
        title: "Mikey's Gang",
        anime: "Tokyo Revengers",
        price: 3500,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Mikey's_Gang_Tokyo_Revengers_Oversized_T-Shirt.jpg",
        rating: 4,
        original_price: 7000,
        discount_percent: 50
    },
    {
        _id: 'bf8e09e0-c042-4f35-8bd6-2db0d8f037fd',
        title: "Toman Logo",
        anime: "Tokyo Revengers",
        price: 4000,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Toman_Logo_Tokyo_Revengers_Oversized_T-Shirt.jpg",
        rating: 4,
        original_price: 8000,
        discount_percent: 50
    },
    {
        _id: '0810adfb-fb3b-42bf-abe5-80bddbf8e62a',
        title: "Tokyo Manji Gang",
        anime: "Tokyo Revengers",
        price: 900,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Tokyo_Manji_Gang_Tokyo_Revengers_Sticker.jpg",
        rating: 5,
        original_price: 1500,
        discount_percent: 40
    },
    {
        _id: 'a36b31d7-3c0b-4ac0-a0a9-2f7c1cb67ba7',
        title: "Time Leap",
        anime: "Tokyo Revengers",
        price: 800,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Time_Leap_Tokyo_Revengers_Sticker.jpg",
        rating: 4,
        original_price: 1777,
        discount_percent: 55
    },
    {
        _id: 'd5a3a48e-6f65-48f7-8077-bc55c64ba03c',
        title: "Takemichi Hanagaki",
        anime: "Tokyo Revengers",
        price: 5500,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Takemichi_Hanagaki_Tokyo_Revengers_Figurine.jpg",
        rating: 3,
        original_price: 11000,
        discount_percent: 50
    },
    {
        _id: 'a2603448-12ff-4efa-89f4-ce9bd47c16f0',
        title: "Manjiro Sano",
        anime: "Tokyo Revengers",
        price: 5000,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Manjiro_Sano_Tokyo_Revengers_Figurine.jpg",
        rating: 5,
        original_price: 10000,
        discount_percent: 50
    },
    {
        _id: 'bbcb8da3-7a4c-4599-b512-2468cdb2a148',
        title: "All Characters Sk8",
        anime: "SK8 the Infinity", 
        price: 3000,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/All_Characters_SK8_the_Infinity_Oversized_T-Shirt.jpg",
        rating: 4,
        original_price: 5454,
        discount_percent: 45
    },
    {
        _id: '53a8c150-fa54-44f8-94fa-1059b843655c',
        title: "Reki and Langa",
        anime: "SK8 the Infinity",
        price: 3500,
        categoryName: "Oversized T-Shirt",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Reki_and_Langa_SK8_the_Infinity_Oversized_T-Shirt.jpg",
        rating: 5,
        original_price: 7777,
        discount_percent: 55
    },
    {
        _id: '96731ecd-860e-45f5-92ef-d5d098129714',
        title: "Cherry",
        anime: "SK8 the Infinity",
        price: 800,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Cherry_SK8_the_Infinity_Sticker.jpg",
        rating: 5,
        original_price: 1333,
        discount_percent: 40
    },
    {
        _id: '66657a17-9902-4c8d-86ed-a10e67d6e1c6',
        title: "Reki Langa",
        anime: "SK8 the Infinity",
        price: 900,
        categoryName: "Sticker",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Reki_Langa_SK8_the_Infinity_Sticker.jpg",
        rating: 5,
        original_price: 1800,
        discount_percent: 50
    },
    {
        _id: 'ae53855d-9b23-442b-a804-b12ef422e26d',
        title: "Langa Hasegawa",
        anime: "SK8 the Infinity",
        price: 5500,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Langa_Hasegawa_SK8_the_Infinity_Figurine.jpg",
        rating: 4,
        original_price: 9166,
        discount_percent: 40
    },
    {
        _id: 'dc22684c-7a61-4cd5-a826-db8498807cf6',
        title: "Reki Kyan",
        anime: "SK8 the Infinity",
        price: 5000,
        categoryName: "Figurine",
        imageLink: "https://raw.githubusercontent.com/KamiyaGaikwad/ChibiKart/master/src/assets/Reki_Kyan_SK8_the_Infinity_Figurine.png",
        rating: 4,
        original_price: 9090,
        discount_percent: 45
    }
];
